version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "web"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "server"
    schedule:
      interval: "daily"
