run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    - godox
    - lll
    - wsl
    - depguard
    - gci
    - nlreturn
    - ireturn
    - varnamelen
    - perfsprint
    - exhaustruct
    - funlen
    - tenv
