// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file api/v1/notifications.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_api_v1_options } from "./options_pb";
import { file_api_v1_shared } from "./shared_pb";
import { file_api_v1_workouts } from "./workouts_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/notifications.proto.
 */
export const file_api_v1_notifications: GenFile = /*@__PURE__*/
  fileDesc("ChphcGkvdjEvbm90aWZpY2F0aW9ucy5wcm90bxIGYXBpLnYxIioKGVVucmVhZE5vdGlmaWNhdGlvbnNTdHJlYW0SDQoFY291bnQYASABKAMybwoTTm90aWZpY2F0aW9uU2VydmljZRJYChNVbnJlYWROb3RpZmljYXRpb25zEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GiEuYXBpLnYxLlVucmVhZE5vdGlmaWNhdGlvbnNTdHJlYW0iBIi1GAEwAUKTAQoKY29tLmFwaS52MUISTm90aWZpY2F0aW9uc1Byb3RvUAFaOGdpdGh1Yi5jb20vY3Jsc3NuL2dldHN0cm9uZ2VyL3NlcnZlci9wa2cvcGIvYXBpL3YxO2FwaXYxogIDQVhYqgIGQXBpLlYxygIGQXBpXFYx4gISQXBpXFYxXEdQQk1ldGFkYXRh6gIHQXBpOjpWMWIGcHJvdG8z", [file_api_v1_options, file_api_v1_shared, file_api_v1_workouts, file_google_protobuf_timestamp, file_google_protobuf_empty, file_buf_validate_validate]);

/**
 * @generated from message api.v1.UnreadNotificationsStream
 */
export type UnreadNotificationsStream = Message<"api.v1.UnreadNotificationsStream"> & {
  /**
   * @generated from field: int64 count = 1;
   */
  count: bigint;
};

/**
 * Describes the message api.v1.UnreadNotificationsStream.
 * Use `create(UnreadNotificationsStreamSchema)` to create a new message.
 */
export const UnreadNotificationsStreamSchema: GenMessage<UnreadNotificationsStream> = /*@__PURE__*/
  messageDesc(file_api_v1_notifications, 0);

/**
 * @generated from service api.v1.NotificationService
 */
export const NotificationService: GenService<{
  /**
   * @generated from rpc api.v1.NotificationService.UnreadNotifications
   */
  unreadNotifications: {
    methodKind: "server_streaming";
    input: typeof EmptySchema;
    output: typeof UnreadNotificationsStreamSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_notifications, 0);

