// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file api/v1/shared.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/shared.proto.
 */
export const file_api_v1_shared: GenFile = /*@__PURE__*/
  fileDesc("ChNhcGkvdjEvc2hhcmVkLnByb3RvEgZhcGkudjEiXwoMRXhlcmNpc2VTZXRzEioKCGV4ZXJjaXNlGAEgASgLMhAuYXBpLnYxLkV4ZXJjaXNlQga6SAPIAQESIwoEc2V0cxgCIAMoCzILLmFwaS52MS5TZXRCCLpIBZIBAggBIj0KCEV4ZXJjaXNlEhQKAmlkGAEgASgJQgi6SAVyA7ABARIMCgRuYW1lGAIgASgJEg0KBWxhYmVsGAMgASgJIiwKA1NldBIOCgZ3ZWlnaHQYASABKAESFQoEcmVwcxgCIAEoBUIHukgEGgIoASJVCgRVc2VyEhQKAmlkGAEgASgJQgi6SAVyA7ABARIbCgpmaXJzdF9uYW1lGAIgASgJQge6SARyAhABEhoKCWxhc3RfbmFtZRgDIAEoCUIHukgEcgIQAUKMAQoKY29tLmFwaS52MUILU2hhcmVkUHJvdG9QAVo4Z2l0aHViLmNvbS9jcmxzc24vZ2V0c3Ryb25nZXIvc2VydmVyL3BrZy9wYi9hcGkvdjE7YXBpdjGiAgNBWFiqAgZBcGkuVjHKAgZBcGlcVjHiAhJBcGlcVjFcR1BCTWV0YWRhdGHqAgdBcGk6OlYxYgZwcm90bzM", [file_buf_validate_validate]);

/**
 * @generated from message api.v1.ExerciseSets
 */
export type ExerciseSets = Message<"api.v1.ExerciseSets"> & {
  /**
   * @generated from field: api.v1.Exercise exercise = 1;
   */
  exercise?: Exercise;

  /**
   * @generated from field: repeated api.v1.Set sets = 2;
   */
  sets: Set[];
};

/**
 * Describes the message api.v1.ExerciseSets.
 * Use `create(ExerciseSetsSchema)` to create a new message.
 */
export const ExerciseSetsSchema: GenMessage<ExerciseSets> = /*@__PURE__*/
  messageDesc(file_api_v1_shared, 0);

/**
 * @generated from message api.v1.Exercise
 */
export type Exercise = Message<"api.v1.Exercise"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string label = 3;
   */
  label: string;
};

/**
 * Describes the message api.v1.Exercise.
 * Use `create(ExerciseSchema)` to create a new message.
 */
export const ExerciseSchema: GenMessage<Exercise> = /*@__PURE__*/
  messageDesc(file_api_v1_shared, 1);

/**
 * @generated from message api.v1.Set
 */
export type Set = Message<"api.v1.Set"> & {
  /**
   * The weight can be less than zero.
   *
   * @generated from field: double weight = 1;
   */
  weight: number;

  /**
   * @generated from field: int32 reps = 2;
   */
  reps: number;
};

/**
 * Describes the message api.v1.Set.
 * Use `create(SetSchema)` to create a new message.
 */
export const SetSchema: GenMessage<Set> = /*@__PURE__*/
  messageDesc(file_api_v1_shared, 2);

/**
 * @generated from message api.v1.User
 */
export type User = Message<"api.v1.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string first_name = 2;
   */
  firstName: string;

  /**
   * @generated from field: string last_name = 3;
   */
  lastName: string;
};

/**
 * Describes the message api.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_api_v1_shared, 3);

