// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file api/v1/users.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_api_v1_options } from "./options_pb";
import { file_api_v1_shared } from "./shared_pb";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/users.proto.
 */
export const file_api_v1_users: GenFile = /*@__PURE__*/
  fileDesc("ChJhcGkvdjEvdXNlcnMucHJvdG8SBmFwaS52MSIsCg1Gb2xsb3dSZXF1ZXN0EhsKCWZvbGxvd19pZBgBIAEoCUIIukgFcgOwAQEiEAoORm9sbG93UmVzcG9uc2UiMAoPVW5mb2xsb3dSZXF1ZXN0Eh0KC3VuZm9sbG93X2lkGAEgASgJQgi6SAVyA7ABASISChBVbmZvbGxvd1Jlc3BvbnNlIjUKFExpc3RGb2xsb3dlcnNSZXF1ZXN0Eh0KC2ZvbGxvd2VyX2lkGAEgASgJQgi6SAVyA7ABASI4ChVMaXN0Rm9sbG93ZXJzUmVzcG9uc2USHwoJZm9sbG93ZXJzGAEgAygLMgwuYXBpLnYxLlVzZXIiNQoUTGlzdEZvbGxvd2Vlc1JlcXVlc3QSHQoLZm9sbG93ZWVfaWQYASABKAlCCLpIBXIDsAEBIjgKFUxpc3RGb2xsb3dlZXNSZXNwb25zZRIfCglmb2xsb3dlZXMYASADKAsyDC5hcGkudjEuVXNlciJVCgRVc2VyEhQKAmlkGAEgASgJQgi6SAVyA7ABARIbCgpmaXJzdF9uYW1lGAIgASgJQge6SARyAhABEhoKCWxhc3RfbmFtZRgDIAEoCUIHukgEcgIQATK5AgoLVXNlclNlcnZpY2USPQoGRm9sbG93EhUuYXBpLnYxLkZvbGxvd1JlcXVlc3QaFi5hcGkudjEuRm9sbG93UmVzcG9uc2UiBIi1GAESQwoIVW5mb2xsb3cSFy5hcGkudjEuVW5mb2xsb3dSZXF1ZXN0GhguYXBpLnYxLlVuZm9sbG93UmVzcG9uc2UiBIi1GAESUgoNTGlzdEZvbGxvd2VycxIcLmFwaS52MS5MaXN0Rm9sbG93ZXJzUmVxdWVzdBodLmFwaS52MS5MaXN0Rm9sbG93ZXJzUmVzcG9uc2UiBIi1GAESUgoNTGlzdEZvbGxvd2VlcxIcLmFwaS52MS5MaXN0Rm9sbG93ZWVzUmVxdWVzdBodLmFwaS52MS5MaXN0Rm9sbG93ZWVzUmVzcG9uc2UiBIi1GAFCiwEKCmNvbS5hcGkudjFCClVzZXJzUHJvdG9QAVo4Z2l0aHViLmNvbS9jcmxzc24vZ2V0c3Ryb25nZXIvc2VydmVyL3BrZy9wYi9hcGkvdjE7YXBpdjGiAgNBWFiqAgZBcGkuVjHKAgZBcGlcVjHiAhJBcGlcVjFcR1BCTWV0YWRhdGHqAgdBcGk6OlYxYgZwcm90bzM", [file_api_v1_options, file_api_v1_shared, file_buf_validate_validate]);

/**
 * @generated from message api.v1.FollowRequest
 */
export type FollowRequest = Message<"api.v1.FollowRequest"> & {
  /**
   * @generated from field: string follow_id = 1;
   */
  followId: string;
};

/**
 * Describes the message api.v1.FollowRequest.
 * Use `create(FollowRequestSchema)` to create a new message.
 */
export const FollowRequestSchema: GenMessage<FollowRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_users, 0);

/**
 * @generated from message api.v1.FollowResponse
 */
export type FollowResponse = Message<"api.v1.FollowResponse"> & {
};

/**
 * Describes the message api.v1.FollowResponse.
 * Use `create(FollowResponseSchema)` to create a new message.
 */
export const FollowResponseSchema: GenMessage<FollowResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_users, 1);

/**
 * @generated from message api.v1.UnfollowRequest
 */
export type UnfollowRequest = Message<"api.v1.UnfollowRequest"> & {
  /**
   * @generated from field: string unfollow_id = 1;
   */
  unfollowId: string;
};

/**
 * Describes the message api.v1.UnfollowRequest.
 * Use `create(UnfollowRequestSchema)` to create a new message.
 */
export const UnfollowRequestSchema: GenMessage<UnfollowRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_users, 2);

/**
 * @generated from message api.v1.UnfollowResponse
 */
export type UnfollowResponse = Message<"api.v1.UnfollowResponse"> & {
};

/**
 * Describes the message api.v1.UnfollowResponse.
 * Use `create(UnfollowResponseSchema)` to create a new message.
 */
export const UnfollowResponseSchema: GenMessage<UnfollowResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_users, 3);

/**
 * @generated from message api.v1.ListFollowersRequest
 */
export type ListFollowersRequest = Message<"api.v1.ListFollowersRequest"> & {
  /**
   * @generated from field: string follower_id = 1;
   */
  followerId: string;
};

/**
 * Describes the message api.v1.ListFollowersRequest.
 * Use `create(ListFollowersRequestSchema)` to create a new message.
 */
export const ListFollowersRequestSchema: GenMessage<ListFollowersRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_users, 4);

/**
 * @generated from message api.v1.ListFollowersResponse
 */
export type ListFollowersResponse = Message<"api.v1.ListFollowersResponse"> & {
  /**
   * @generated from field: repeated api.v1.User followers = 1;
   */
  followers: User[];
};

/**
 * Describes the message api.v1.ListFollowersResponse.
 * Use `create(ListFollowersResponseSchema)` to create a new message.
 */
export const ListFollowersResponseSchema: GenMessage<ListFollowersResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_users, 5);

/**
 * @generated from message api.v1.ListFolloweesRequest
 */
export type ListFolloweesRequest = Message<"api.v1.ListFolloweesRequest"> & {
  /**
   * @generated from field: string followee_id = 1;
   */
  followeeId: string;
};

/**
 * Describes the message api.v1.ListFolloweesRequest.
 * Use `create(ListFolloweesRequestSchema)` to create a new message.
 */
export const ListFolloweesRequestSchema: GenMessage<ListFolloweesRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_users, 6);

/**
 * @generated from message api.v1.ListFolloweesResponse
 */
export type ListFolloweesResponse = Message<"api.v1.ListFolloweesResponse"> & {
  /**
   * @generated from field: repeated api.v1.User followees = 1;
   */
  followees: User[];
};

/**
 * Describes the message api.v1.ListFolloweesResponse.
 * Use `create(ListFolloweesResponseSchema)` to create a new message.
 */
export const ListFolloweesResponseSchema: GenMessage<ListFolloweesResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_users, 7);

/**
 * @generated from message api.v1.User
 */
export type User = Message<"api.v1.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string first_name = 2;
   */
  firstName: string;

  /**
   * @generated from field: string last_name = 3;
   */
  lastName: string;
};

/**
 * Describes the message api.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_api_v1_users, 8);

/**
 * @generated from service api.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc api.v1.UserService.Follow
   */
  follow: {
    methodKind: "unary";
    input: typeof FollowRequestSchema;
    output: typeof FollowResponseSchema;
  },
  /**
   * @generated from rpc api.v1.UserService.Unfollow
   */
  unfollow: {
    methodKind: "unary";
    input: typeof UnfollowRequestSchema;
    output: typeof UnfollowResponseSchema;
  },
  /**
   * @generated from rpc api.v1.UserService.ListFollowers
   */
  listFollowers: {
    methodKind: "unary";
    input: typeof ListFollowersRequestSchema;
    output: typeof ListFollowersResponseSchema;
  },
  /**
   * @generated from rpc api.v1.UserService.ListFollowees
   */
  listFollowees: {
    methodKind: "unary";
    input: typeof ListFolloweesRequestSchema;
    output: typeof ListFolloweesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_users, 0);

