// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file api/v1/users.proto (package api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { FollowRequest, FollowResponse, ListFolloweesRequest, ListFolloweesResponse, ListFollowersRequest, ListFollowersResponse, UnfollowRequest, UnfollowResponse } from "./users_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.v1.UserService
 */
export const UserService = {
  typeName: "api.v1.UserService",
  methods: {
    /**
     * @generated from rpc api.v1.UserService.Follow
     */
    follow: {
      name: "Follow",
      I: FollowRequest,
      O: FollowResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.UserService.Unfollow
     */
    unfollow: {
      name: "Unfollow",
      I: UnfollowRequest,
      O: UnfollowResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.UserService.ListFollowers
     */
    listFollowers: {
      name: "ListFollowers",
      I: ListFollowersRequest,
      O: ListFollowersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.UserService.ListFollowees
     */
    listFollowees: {
      name: "ListFollowees",
      I: ListFolloweesRequest,
      O: ListFolloweesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

