// Generated from exercises/*.yaml by `mise run gen:exercises`. Do not edit.

import type { LibraryExercise } from '@/exercises/types'

import { ExerciseMetric } from '@/proto/api/v1/shared_pb'

export const catalogue: readonly LibraryExercise[] = [
  {
    key: 'barbell-curl',
    names: { en: 'Barbell curl', sv: 'Bicepscurl med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['arms', 'biceps', 'isolation'],
  },
  {
    key: 'ez-bar-curl',
    names: { en: 'EZ-bar curl', sv: 'Bicepscurl med EZ-stång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['ez-bar'],
    tags: ['arms', 'biceps', 'isolation'],
  },
  {
    key: 'barbell-reverse-curl',
    names: { en: 'Reverse curl', sv: 'Omvänd curl med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['arms', 'forearms', 'biceps', 'isolation'],
  },
  {
    key: 'dumbbell-curl',
    names: { en: 'Dumbbell curl', sv: 'Bicepscurl med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['arms', 'biceps', 'isolation'],
  },
  {
    key: 'dumbbell-hammer-curl',
    names: { en: 'Dumbbell hammer curl', sv: 'Hammarcurl med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['arms', 'biceps', 'forearms', 'isolation'],
  },
  {
    key: 'dumbbell-incline-curl',
    names: { en: 'Dumbbell incline curl', sv: 'Lutande bicepscurl med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell', 'incline-bench'],
    tags: ['arms', 'biceps', 'isolation'],
  },
  {
    key: 'dumbbell-concentration-curl',
    names: { en: 'Concentration curl', sv: 'Koncentrationscurl med hantel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['arms', 'biceps', 'unilateral', 'isolation'],
  },
  {
    key: 'dumbbell-spider-curl',
    names: { en: 'Spider curl', sv: 'Spidercurl med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell', 'incline-bench'],
    tags: ['arms', 'biceps', 'isolation'],
  },
  {
    key: 'zottman-curl',
    names: { en: 'Zottman curl', sv: 'Zottmancurl' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['arms', 'biceps', 'forearms', 'isolation'],
  },
  {
    key: 'preacher-curl',
    names: { en: 'Preacher curl', sv: 'Scottcurl' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['ez-bar', 'preacher-bench'],
    tags: ['arms', 'biceps', 'isolation'],
  },
  {
    key: 'machine-preacher-curl',
    names: { en: 'Machine preacher curl', sv: 'Scottcurl i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['arms', 'biceps', 'isolation'],
  },
  {
    key: 'kettlebell-curl',
    names: { en: 'Kettlebell curl', sv: 'Bicepscurl med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['arms', 'biceps', 'isolation'],
  },
  {
    key: 'cable-curl',
    names: { en: 'Cable curl', sv: 'Bicepscurl i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['arms', 'biceps', 'isolation'],
  },
  {
    key: 'cable-hammer-curl',
    names: { en: 'Cable hammer curl', sv: 'Hammarcurl i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['arms', 'biceps', 'forearms', 'isolation'],
  },
  {
    key: 'band-curl',
    names: { en: 'Band curl', sv: 'Bicepscurl med gummiband' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['arms', 'biceps', 'isolation'],
  },
  {
    key: 'barbell-close-grip-bench-press',
    names: { en: 'Close-grip bench press', sv: 'Bänkpress med smalt grepp' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell', 'bench'],
    tags: ['arms', 'triceps', 'horizontal-push', 'front-delts', 'compound'],
  },
  {
    key: 'ez-bar-skull-crusher',
    names: { en: 'EZ-bar skull crusher', sv: 'Fransk press med EZ-stång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['ez-bar', 'bench'],
    tags: ['arms', 'triceps', 'isolation'],
  },
  {
    key: 'dumbbell-lying-triceps-extension',
    names: { en: 'Dumbbell lying triceps extension', sv: 'Liggande tricepspress med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell', 'bench'],
    tags: ['arms', 'triceps', 'isolation'],
  },
  {
    key: 'dumbbell-overhead-triceps-extension',
    names: {
      en: 'Dumbbell overhead triceps extension',
      sv: 'Tricepspress över huvudet med hantel',
    },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['arms', 'triceps', 'isolation'],
  },
  {
    key: 'dumbbell-triceps-kickback',
    names: { en: 'Dumbbell triceps kickback', sv: 'Tricepskickback med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['arms', 'triceps', 'isolation'],
  },
  {
    key: 'kettlebell-overhead-triceps-extension',
    names: {
      en: 'Kettlebell overhead triceps extension',
      sv: 'Tricepspress över huvudet med kettlebell',
    },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['arms', 'triceps', 'isolation'],
  },
  {
    key: 'cable-triceps-pushdown',
    names: { en: 'Cable triceps pushdown', sv: 'Tricepspress i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['arms', 'triceps', 'isolation'],
  },
  {
    key: 'cable-overhead-triceps-extension',
    names: { en: 'Cable overhead triceps extension', sv: 'Tricepspress över huvudet i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['arms', 'triceps', 'isolation'],
  },
  {
    key: 'cable-single-arm-pushdown',
    names: { en: 'Single-arm cable pushdown', sv: 'Enarms tricepspress i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['arms', 'triceps', 'unilateral', 'isolation'],
  },
  {
    key: 'machine-triceps-extension',
    names: { en: 'Machine triceps extension', sv: 'Tricepspress i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['arms', 'triceps', 'isolation'],
  },
  {
    key: 'machine-assisted-dip',
    names: { en: 'Machine assisted dip', sv: 'Dips i assisterad maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['arms', 'triceps', 'vertical-push', 'compound'],
  },
  {
    key: 'band-triceps-pushdown',
    names: { en: 'Band triceps pushdown', sv: 'Tricepspress med gummiband' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['arms', 'triceps', 'isolation'],
  },
  {
    key: 'triceps-dip',
    names: { en: 'Triceps dip', sv: 'Dips för triceps' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['bodyweight', 'dip-bars'],
    tags: ['arms', 'triceps', 'vertical-push', 'bodyweight', 'compound'],
  },
  {
    key: 'bench-dip',
    names: { en: 'Bench dip', sv: 'Bänkdips' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight', 'bench'],
    tags: ['arms', 'triceps', 'bodyweight'],
  },
  {
    key: 'ring-dip',
    names: { en: 'Ring dip', sv: 'Dips i ringar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['rings', 'bodyweight'],
    tags: ['arms', 'triceps', 'vertical-push', 'bodyweight'],
  },
  {
    key: 'diamond-push-up',
    names: { en: 'Diamond push-up', sv: 'Diamantarmhävning' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['arms', 'triceps', 'horizontal-push', 'bodyweight'],
  },
  {
    key: 'barbell-wrist-curl',
    names: { en: 'Barbell wrist curl', sv: 'Handledscurl med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell', 'bench'],
    tags: ['arms', 'forearms', 'isolation'],
  },
  {
    key: 'dumbbell-reverse-wrist-curl',
    names: { en: 'Dumbbell reverse wrist curl', sv: 'Omvänd handledscurl med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell', 'bench'],
    tags: ['arms', 'forearms', 'isolation'],
  },
  {
    key: 'plate-pinch-hold',
    names: { en: 'Plate pinch hold', sv: 'Greppstyrka med viktskiva' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.TIME],
    equipment: ['plate'],
    tags: ['arms', 'forearms', 'isometric'],
  },
  {
    key: 'barbell-row',
    names: { en: 'Barbell row', sv: 'Skivstångsrodd' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['back', 'horizontal-pull', 'lats', 'rhomboids', 'biceps', 'compound'],
  },
  {
    key: 'pendlay-row',
    names: { en: 'Pendlay row', sv: 'Pendlayrodd' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['back', 'horizontal-pull', 'lats', 'rhomboids', 'compound'],
  },
  {
    key: 'underhand-barbell-row',
    names: { en: 'Underhand barbell row', sv: 'Skivstångsrodd med underhandsgrepp' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['back', 'horizontal-pull', 'lats', 'biceps', 'compound'],
  },
  {
    key: 'seal-row',
    names: { en: 'Seal row', sv: 'Sälrodd' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell', 'bench'],
    tags: ['back', 'horizontal-pull', 'lats', 'rhomboids', 'compound'],
  },
  {
    key: 'landmine-row',
    names: { en: 'Landmine row', sv: 'Landminerodd' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['landmine', 'barbell'],
    tags: ['back', 'horizontal-pull', 'lats', 'rhomboids', 'compound'],
  },
  {
    key: 'barbell-rack-pull',
    names: { en: 'Rack pull', sv: 'Rack pull' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell', 'squat-rack'],
    tags: ['back', 'hinge', 'traps', 'lats', 'lower-back', 'compound'],
  },
  {
    key: 'dumbbell-row',
    names: { en: 'Dumbbell row', sv: 'Hantelrodd' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell', 'bench'],
    tags: ['back', 'horizontal-pull', 'lats', 'rhomboids', 'biceps', 'unilateral', 'compound'],
  },
  {
    key: 'dumbbell-chest-supported-row',
    names: { en: 'Dumbbell chest-supported row', sv: 'Bröststödd hantelrodd' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell', 'incline-bench'],
    tags: ['back', 'horizontal-pull', 'lats', 'rhomboids', 'compound'],
  },
  {
    key: 'kettlebell-row',
    names: { en: 'Kettlebell row', sv: 'Kettlebellrodd' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['back', 'horizontal-pull', 'lats', 'biceps', 'unilateral', 'compound'],
  },
  {
    key: 'kettlebell-renegade-row',
    names: { en: 'Kettlebell renegade row', sv: 'Renegadrodd med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['back', 'horizontal-pull', 'lats', 'abs', 'compound'],
  },
  {
    key: 'seated-cable-row',
    names: { en: 'Seated cable row', sv: 'Sittande kabelrodd' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['back', 'horizontal-pull', 'lats', 'rhomboids', 'biceps', 'compound'],
  },
  {
    key: 'cable-single-arm-row',
    names: { en: 'Single-arm cable row', sv: 'Enarmsrodd i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['back', 'horizontal-pull', 'lats', 'unilateral', 'compound'],
  },
  {
    key: 'cable-straight-arm-pulldown',
    names: { en: 'Straight-arm pulldown', sv: 'Rakarmsdrag i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['back', 'lats', 'serratus', 'isolation'],
  },
  {
    key: 'machine-chest-supported-row',
    names: { en: 'Machine chest-supported row', sv: 'Bröststödd rodd i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['back', 'horizontal-pull', 'lats', 'rhomboids', 'compound'],
  },
  {
    key: 't-bar-row',
    names: { en: 'T-bar row', sv: 'T-bar-rodd' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['back', 'horizontal-pull', 'lats', 'rhomboids', 'compound'],
  },
  {
    key: 'band-seated-row',
    names: { en: 'Band seated row', sv: 'Sittande rodd med gummiband' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['back', 'horizontal-pull', 'lats', 'rhomboids'],
  },
  {
    key: 'band-bent-over-row',
    names: { en: 'Band bent-over row', sv: 'Framåtlutad rodd med gummiband' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['back', 'horizontal-pull', 'lats', 'biceps'],
  },
  {
    key: 'inverted-row',
    names: { en: 'Inverted row', sv: 'Omvänd rodd' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['bodyweight', 'barbell', 'squat-rack'],
    tags: ['back', 'horizontal-pull', 'lats', 'rhomboids', 'bodyweight', 'compound'],
  },
  {
    key: 'ring-row',
    names: { en: 'Ring row', sv: 'Rodd i ringar' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['rings', 'bodyweight'],
    tags: ['back', 'horizontal-pull', 'lats', 'bodyweight'],
  },
  {
    key: 'suspension-row',
    names: { en: 'Suspension trainer row', sv: 'Rodd i slingtränare' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['suspension-trainer', 'bodyweight'],
    tags: ['back', 'horizontal-pull', 'lats', 'bodyweight'],
  },
  {
    key: 'pull-up',
    names: { en: 'Pull-up', sv: 'Chins med överhandsgrepp' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['bodyweight', 'pull-up-bar'],
    tags: ['back', 'vertical-pull', 'lats', 'biceps', 'bodyweight', 'compound'],
  },
  {
    key: 'chin-up',
    names: { en: 'Chin-up', sv: 'Chins med underhandsgrepp' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['bodyweight', 'pull-up-bar'],
    tags: ['back', 'vertical-pull', 'lats', 'biceps', 'bodyweight', 'compound'],
  },
  {
    key: 'wide-grip-pull-up',
    names: { en: 'Wide-grip pull-up', sv: 'Chins med brett grepp' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['bodyweight', 'pull-up-bar'],
    tags: ['back', 'vertical-pull', 'lats', 'bodyweight', 'compound'],
  },
  {
    key: 'neutral-grip-pull-up',
    names: { en: 'Neutral-grip pull-up', sv: 'Chins med neutralt grepp' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['bodyweight', 'pull-up-bar'],
    tags: ['back', 'vertical-pull', 'lats', 'biceps', 'bodyweight', 'compound'],
  },
  {
    key: 'weighted-pull-up',
    names: { en: 'Weighted pull-up', sv: 'Chins med vikt' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['bodyweight', 'pull-up-bar', 'weight-vest'],
    tags: ['back', 'vertical-pull', 'lats', 'biceps', 'compound'],
  },
  {
    key: 'machine-assisted-pull-up',
    names: { en: 'Machine assisted pull-up', sv: 'Chins i assisterad maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['back', 'vertical-pull', 'lats', 'biceps', 'compound'],
  },
  {
    key: 'band-assisted-pull-up',
    names: { en: 'Band assisted pull-up', sv: 'Chins med gummiband' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['band', 'pull-up-bar', 'bodyweight'],
    tags: ['back', 'vertical-pull', 'lats', 'biceps'],
  },
  {
    key: 'lat-pulldown',
    names: { en: 'Lat pulldown', sv: 'Latsdrag' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['back', 'vertical-pull', 'lats', 'biceps', 'compound'],
  },
  {
    key: 'close-grip-lat-pulldown',
    names: { en: 'Close-grip lat pulldown', sv: 'Latsdrag med smalt grepp' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['back', 'vertical-pull', 'lats', 'biceps', 'compound'],
  },
  {
    key: 'wide-grip-lat-pulldown',
    names: { en: 'Wide-grip lat pulldown', sv: 'Latsdrag med brett grepp' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['back', 'vertical-pull', 'lats', 'compound'],
  },
  {
    key: 'machine-lat-pulldown',
    names: { en: 'Machine lat pulldown', sv: 'Latsdrag i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['back', 'vertical-pull', 'lats', 'compound'],
  },
  {
    key: 'band-lat-pulldown',
    names: { en: 'Band lat pulldown', sv: 'Latsdrag med gummiband' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['back', 'vertical-pull', 'lats'],
  },
  {
    key: 'barbell-shrug',
    names: { en: 'Barbell shrug', sv: 'Axelryck med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['back', 'traps', 'isolation'],
  },
  {
    key: 'dumbbell-shrug',
    names: { en: 'Dumbbell shrug', sv: 'Axelryck med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['back', 'traps', 'isolation'],
  },
  {
    key: 'machine-shrug',
    names: { en: 'Machine shrug', sv: 'Axelryck i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['back', 'traps', 'isolation'],
  },
  {
    key: 'run',
    names: { en: 'Run', sv: 'Löpning' },
    metrics: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
    equipment: ['bodyweight'],
    tags: ['cardio', 'conditioning', 'quadriceps', 'calves', 'bodyweight'],
  },
  {
    key: 'sprint',
    names: { en: 'Sprint', sv: 'Sprint' },
    metrics: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
    equipment: ['bodyweight'],
    tags: ['cardio', 'conditioning', 'quadriceps', 'hamstrings', 'bodyweight'],
  },
  {
    key: 'hill-sprint',
    names: { en: 'Hill sprint', sv: 'Backsprint' },
    metrics: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
    equipment: ['bodyweight'],
    tags: ['cardio', 'conditioning', 'quadriceps', 'calves', 'bodyweight'],
  },
  {
    key: 'walk',
    names: { en: 'Walk', sv: 'Promenad' },
    metrics: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
    equipment: ['bodyweight'],
    tags: ['cardio', 'conditioning', 'calves', 'bodyweight'],
  },
  {
    key: 'ruck-walk',
    names: { en: 'Ruck walk', sv: 'Gång med viktväst' },
    metrics: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
    equipment: ['weight-vest', 'bodyweight'],
    tags: ['cardio', 'conditioning', 'calves', 'traps'],
  },
  {
    key: 'treadmill-run',
    names: { en: 'Treadmill run', sv: 'Löpning på löpband' },
    metrics: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
    equipment: ['treadmill'],
    tags: ['cardio', 'conditioning', 'quadriceps', 'calves'],
  },
  {
    key: 'treadmill-walk',
    names: { en: 'Treadmill walk', sv: 'Gång på löpband' },
    metrics: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
    equipment: ['treadmill'],
    tags: ['cardio', 'conditioning', 'calves'],
  },
  {
    key: 'incline-treadmill-walk',
    names: { en: 'Incline treadmill walk', sv: 'Lutande gång på löpband' },
    metrics: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
    equipment: ['treadmill'],
    tags: ['cardio', 'conditioning', 'hamstrings', 'calves'],
  },
  {
    key: 'rowing-machine',
    names: { en: 'Rowing machine', sv: 'Rodd i roddmaskin' },
    metrics: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
    equipment: ['rower'],
    tags: ['cardio', 'conditioning', 'lats', 'quadriceps'],
  },
  {
    key: 'ski-erg',
    names: { en: 'Ski erg', sv: 'Skiergometer' },
    metrics: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
    equipment: ['ski-erg'],
    tags: ['cardio', 'conditioning', 'lats', 'triceps'],
  },
  {
    key: 'stationary-bike',
    names: { en: 'Stationary bike', sv: 'Motionscykel' },
    metrics: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
    equipment: ['stationary-bike'],
    tags: ['cardio', 'conditioning', 'quadriceps'],
  },
  {
    key: 'air-bike',
    names: { en: 'Air bike', sv: 'Air bike' },
    metrics: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
    equipment: ['air-bike'],
    tags: ['cardio', 'conditioning', 'quadriceps', 'lats'],
  },
  {
    key: 'elliptical-trainer',
    names: { en: 'Elliptical trainer', sv: 'Crosstrainer' },
    metrics: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
    equipment: ['elliptical'],
    tags: ['cardio', 'conditioning', 'quadriceps'],
  },
  {
    key: 'stair-climber',
    names: { en: 'Stair climber', sv: 'Trappmaskin' },
    metrics: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
    equipment: ['stair-climber'],
    tags: ['cardio', 'conditioning', 'quadriceps', 'calves'],
  },
  {
    key: 'jump-rope',
    names: { en: 'Jump rope', sv: 'Hopprep' },
    metrics: [ExerciseMetric.TIME],
    equipment: ['jump-rope'],
    tags: ['cardio', 'conditioning', 'calves'],
  },
  {
    key: 'double-under',
    names: { en: 'Double under', sv: 'Dubbelhopp med hopprep' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['jump-rope'],
    tags: ['cardio', 'conditioning', 'calves'],
  },
  {
    key: 'high-knees',
    names: { en: 'High knees', sv: 'Höga knän' },
    metrics: [ExerciseMetric.TIME],
    equipment: ['bodyweight'],
    tags: ['cardio', 'conditioning', 'hip-flexors', 'bodyweight'],
  },
  {
    key: 'jumping-jack',
    names: { en: 'Jumping jack', sv: 'Jumping jacks' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['cardio', 'conditioning', 'calves', 'bodyweight'],
  },
  {
    key: 'barbell-bench-press',
    names: { en: 'Barbell bench press', sv: 'Bänkpress med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell', 'bench'],
    tags: ['chest', 'horizontal-push', 'triceps', 'front-delts', 'compound'],
  },
  {
    key: 'barbell-incline-bench-press',
    names: { en: 'Barbell incline bench press', sv: 'Lutande bänkpress med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell', 'incline-bench'],
    tags: ['chest', 'horizontal-push', 'upper-chest', 'triceps', 'front-delts', 'compound'],
  },
  {
    key: 'barbell-decline-bench-press',
    names: { en: 'Barbell decline bench press', sv: 'Nedåtlutande bänkpress med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell', 'decline-bench'],
    tags: ['chest', 'horizontal-push', 'lower-chest', 'triceps', 'compound'],
  },
  {
    key: 'barbell-floor-press',
    names: { en: 'Barbell floor press', sv: 'Golvpress med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['chest', 'horizontal-push', 'triceps', 'compound'],
  },
  {
    key: 'smith-machine-bench-press',
    names: { en: 'Smith machine bench press', sv: 'Bänkpress i smithmaskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['smith-machine', 'bench'],
    tags: ['chest', 'horizontal-push', 'triceps', 'front-delts', 'compound'],
  },
  {
    key: 'dumbbell-bench-press',
    names: { en: 'Dumbbell bench press', sv: 'Bänkpress med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell', 'bench'],
    tags: ['chest', 'horizontal-push', 'triceps', 'front-delts', 'compound'],
  },
  {
    key: 'dumbbell-incline-bench-press',
    names: { en: 'Dumbbell incline bench press', sv: 'Lutande bänkpress med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell', 'incline-bench'],
    tags: ['chest', 'horizontal-push', 'upper-chest', 'triceps', 'compound'],
  },
  {
    key: 'dumbbell-decline-bench-press',
    names: { en: 'Dumbbell decline bench press', sv: 'Nedåtlutande bänkpress med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell', 'decline-bench'],
    tags: ['chest', 'horizontal-push', 'lower-chest', 'triceps', 'compound'],
  },
  {
    key: 'dumbbell-floor-press',
    names: { en: 'Dumbbell floor press', sv: 'Golvpress med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['chest', 'horizontal-push', 'triceps', 'compound'],
  },
  {
    key: 'dumbbell-fly',
    names: { en: 'Dumbbell fly', sv: 'Hantelflyes' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell', 'bench'],
    tags: ['chest', 'isolation'],
  },
  {
    key: 'dumbbell-incline-fly',
    names: { en: 'Dumbbell incline fly', sv: 'Lutande hantelflyes' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell', 'incline-bench'],
    tags: ['chest', 'upper-chest', 'isolation'],
  },
  {
    key: 'dumbbell-pullover',
    names: { en: 'Dumbbell pullover', sv: 'Pullover med hantel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell', 'bench'],
    tags: ['chest', 'lats', 'serratus', 'isolation'],
  },
  {
    key: 'kettlebell-floor-press',
    names: { en: 'Kettlebell floor press', sv: 'Golvpress med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['chest', 'horizontal-push', 'triceps', 'compound'],
  },
  {
    key: 'svend-press',
    names: { en: 'Svend press', sv: 'Svendpress' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['plate'],
    tags: ['chest', 'horizontal-push', 'isolation'],
  },
  {
    key: 'cable-chest-press',
    names: { en: 'Cable chest press', sv: 'Bröstpress i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['chest', 'horizontal-push', 'triceps', 'compound'],
  },
  {
    key: 'cable-crossover',
    names: { en: 'Cable crossover', sv: 'Kabelcrossover' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['chest', 'isolation'],
  },
  {
    key: 'cable-low-to-high-fly',
    names: { en: 'Cable low-to-high fly', sv: 'Kabelflyes nedifrån och upp' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['chest', 'upper-chest', 'isolation'],
  },
  {
    key: 'cable-high-to-low-fly',
    names: { en: 'Cable high-to-low fly', sv: 'Kabelflyes uppifrån och ner' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['chest', 'lower-chest', 'isolation'],
  },
  {
    key: 'machine-chest-press',
    names: { en: 'Machine chest press', sv: 'Bröstpress i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['chest', 'horizontal-push', 'triceps', 'compound'],
  },
  {
    key: 'machine-incline-chest-press',
    names: { en: 'Machine incline chest press', sv: 'Lutande bröstpress i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['chest', 'horizontal-push', 'upper-chest', 'triceps', 'compound'],
  },
  {
    key: 'machine-chest-fly',
    names: { en: 'Machine chest fly', sv: 'Bröstflyes i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['chest', 'isolation'],
  },
  {
    key: 'band-chest-press',
    names: { en: 'Band chest press', sv: 'Bröstpress med gummiband' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['chest', 'horizontal-push', 'triceps', 'compound'],
  },
  {
    key: 'band-chest-fly',
    names: { en: 'Band chest fly', sv: 'Bröstflyes med gummiband' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['chest', 'isolation'],
  },
  {
    key: 'push-up',
    names: { en: 'Push-up', sv: 'Armhävning' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['chest', 'horizontal-push', 'triceps', 'front-delts', 'bodyweight', 'compound'],
  },
  {
    key: 'weighted-push-up',
    names: { en: 'Weighted push-up', sv: 'Armhävning med vikt' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['bodyweight', 'weight-vest'],
    tags: ['chest', 'horizontal-push', 'triceps', 'bodyweight', 'compound'],
  },
  {
    key: 'incline-push-up',
    names: { en: 'Incline push-up', sv: 'Armhävning med händerna högt' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight', 'box'],
    tags: ['chest', 'horizontal-push', 'triceps', 'bodyweight'],
  },
  {
    key: 'decline-push-up',
    names: { en: 'Decline push-up', sv: 'Armhävning med fötterna högt' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight', 'box'],
    tags: ['chest', 'horizontal-push', 'upper-chest', 'triceps', 'bodyweight'],
  },
  {
    key: 'plyometric-push-up',
    names: { en: 'Plyometric push-up', sv: 'Explosiv armhävning' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['chest', 'horizontal-push', 'plyometric', 'triceps', 'bodyweight'],
  },
  {
    key: 'ring-push-up',
    names: { en: 'Ring push-up', sv: 'Armhävning i ringar' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight', 'rings'],
    tags: ['chest', 'horizontal-push', 'triceps', 'bodyweight'],
  },
  {
    key: 'suspension-chest-press',
    names: { en: 'Suspension trainer chest press', sv: 'Bröstpress i slingtränare' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['suspension-trainer', 'bodyweight'],
    tags: ['chest', 'horizontal-push', 'triceps', 'bodyweight'],
  },
  {
    key: 'chest-dip',
    names: { en: 'Chest dip', sv: 'Dips för bröst' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['bodyweight', 'dip-bars'],
    tags: ['chest', 'lower-chest', 'vertical-push', 'triceps', 'bodyweight', 'compound'],
  },
  {
    key: 'plank',
    names: { en: 'Plank', sv: 'Planka' },
    metrics: [ExerciseMetric.TIME],
    equipment: ['bodyweight'],
    tags: ['core', 'abs', 'anti-extension', 'isometric', 'bodyweight'],
  },
  {
    key: 'weighted-plank',
    names: { en: 'Weighted plank', sv: 'Planka med vikt' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.TIME],
    equipment: ['bodyweight', 'plate'],
    tags: ['core', 'abs', 'anti-extension', 'isometric'],
  },
  {
    key: 'side-plank',
    names: { en: 'Side plank', sv: 'Sidoplanka' },
    metrics: [ExerciseMetric.TIME],
    equipment: ['bodyweight'],
    tags: ['core', 'obliques', 'anti-lateral-flexion', 'isometric', 'bodyweight'],
  },
  {
    key: 'copenhagen-plank',
    names: { en: 'Copenhagen plank', sv: 'Copenhagenplanka' },
    metrics: [ExerciseMetric.TIME],
    equipment: ['bodyweight', 'bench'],
    tags: ['core', 'adductors', 'anti-lateral-flexion', 'isometric', 'bodyweight'],
  },
  {
    key: 'hollow-body-hold',
    names: { en: 'Hollow body hold', sv: 'Hollow hold' },
    metrics: [ExerciseMetric.TIME],
    equipment: ['bodyweight'],
    tags: ['core', 'abs', 'anti-extension', 'isometric', 'bodyweight'],
  },
  {
    key: 'l-sit',
    names: { en: 'L-sit', sv: 'L-sit' },
    metrics: [ExerciseMetric.TIME],
    equipment: ['bodyweight', 'dip-bars'],
    tags: ['core', 'abs', 'hip-flexors', 'isometric', 'bodyweight'],
  },
  {
    key: 'dead-bug',
    names: { en: 'Dead bug', sv: 'Dead bug' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['core', 'abs', 'anti-extension', 'bodyweight'],
  },
  {
    key: 'bird-dog',
    names: { en: 'Bird dog', sv: 'Bird dog' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['core', 'abs', 'anti-rotation', 'bodyweight'],
  },
  {
    key: 'crunch',
    names: { en: 'Crunch', sv: 'Crunch' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['core', 'abs', 'bodyweight'],
  },
  {
    key: 'sit-up',
    names: { en: 'Sit-up', sv: 'Situps' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['core', 'abs', 'hip-flexors', 'bodyweight'],
  },
  {
    key: 'bicycle-crunch',
    names: { en: 'Bicycle crunch', sv: 'Cykelcrunch' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['core', 'abs', 'obliques', 'bodyweight'],
  },
  {
    key: 'reverse-crunch',
    names: { en: 'Reverse crunch', sv: 'Omvänd crunch' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['core', 'abs', 'hip-flexors', 'bodyweight'],
  },
  {
    key: 'v-up',
    names: { en: 'V-up', sv: 'V-ups' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['core', 'abs', 'hip-flexors', 'bodyweight'],
  },
  {
    key: 'flutter-kick',
    names: { en: 'Flutter kick', sv: 'Saxsparkar' },
    metrics: [ExerciseMetric.TIME],
    equipment: ['bodyweight'],
    tags: ['core', 'abs', 'hip-flexors', 'bodyweight'],
  },
  {
    key: 'mountain-climber',
    names: { en: 'Mountain climber', sv: 'Mountain climbers' },
    metrics: [ExerciseMetric.TIME],
    equipment: ['bodyweight'],
    tags: ['core', 'abs', 'conditioning', 'bodyweight'],
  },
  {
    key: 'hanging-knee-raise',
    names: { en: 'Hanging knee raise', sv: 'Hängande knälyft' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight', 'pull-up-bar'],
    tags: ['core', 'abs', 'hip-flexors', 'bodyweight'],
  },
  {
    key: 'hanging-leg-raise',
    names: { en: 'Hanging leg raise', sv: 'Hängande benlyft' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['bodyweight', 'pull-up-bar'],
    tags: ['core', 'abs', 'hip-flexors', 'bodyweight'],
  },
  {
    key: 'toes-to-bar',
    names: { en: 'Toes to bar', sv: 'Tår till stång' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight', 'pull-up-bar'],
    tags: ['core', 'abs', 'hip-flexors', 'bodyweight'],
  },
  {
    key: 'ab-wheel-rollout',
    names: { en: 'Ab wheel rollout', sv: 'Utrullning med rullhjul' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['ab-wheel'],
    tags: ['core', 'abs', 'anti-extension'],
  },
  {
    key: 'barbell-rollout',
    names: { en: 'Barbell rollout', sv: 'Utrullning med skivstång' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['core', 'abs', 'anti-extension'],
  },
  {
    key: 'stability-ball-rollout',
    names: { en: 'Stability ball rollout', sv: 'Utrullning med gymboll' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['stability-ball'],
    tags: ['core', 'abs', 'anti-extension'],
  },
  {
    key: 'stability-ball-crunch',
    names: { en: 'Stability ball crunch', sv: 'Crunch på gymboll' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['stability-ball'],
    tags: ['core', 'abs'],
  },
  {
    key: 'cable-crunch',
    names: { en: 'Cable crunch', sv: 'Crunch i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['core', 'abs', 'isolation'],
  },
  {
    key: 'cable-woodchop',
    names: { en: 'Cable woodchop', sv: 'Vedhuggning i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['core', 'obliques', 'rotation'],
  },
  {
    key: 'cable-pallof-press',
    names: { en: 'Cable Pallof press', sv: 'Pallofpress i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['core', 'abs', 'anti-rotation'],
  },
  {
    key: 'band-pallof-press',
    names: { en: 'Band Pallof press', sv: 'Pallofpress med gummiband' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['core', 'abs', 'anti-rotation'],
  },
  {
    key: 'band-woodchop',
    names: { en: 'Band woodchop', sv: 'Vedhuggning med gummiband' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['core', 'obliques', 'rotation'],
  },
  {
    key: 'machine-crunch',
    names: { en: 'Machine crunch', sv: 'Magböj i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['core', 'abs', 'isolation'],
  },
  {
    key: 'machine-torso-rotation',
    names: { en: 'Machine torso rotation', sv: 'Bålrotation i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['core', 'obliques', 'rotation', 'isolation'],
  },
  {
    key: 'dumbbell-side-bend',
    names: { en: 'Dumbbell side bend', sv: 'Sidoböj med hantel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['core', 'obliques', 'anti-lateral-flexion', 'isolation'],
  },
  {
    key: 'dumbbell-russian-twist',
    names: { en: 'Dumbbell Russian twist', sv: 'Rysk twist med hantel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['core', 'obliques', 'rotation'],
  },
  {
    key: 'medicine-ball-russian-twist',
    names: { en: 'Medicine ball Russian twist', sv: 'Rysk twist med medicinboll' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['medicine-ball'],
    tags: ['core', 'obliques', 'rotation'],
  },
  {
    key: 'dumbbell-farmers-walk',
    names: { en: 'Dumbbell farmers walk', sv: 'Farmers walk med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.DISTANCE],
    equipment: ['dumbbell'],
    tags: ['full-body', 'carry', 'forearms', 'traps', 'compound'],
  },
  {
    key: 'kettlebell-farmers-walk',
    names: { en: 'Kettlebell farmers walk', sv: 'Farmers walk med kettlebells' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.DISTANCE],
    equipment: ['kettlebell'],
    tags: ['full-body', 'carry', 'forearms', 'traps', 'compound'],
  },
  {
    key: 'trap-bar-farmers-walk',
    names: { en: 'Trap bar farmers walk', sv: 'Farmers walk med trap bar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.DISTANCE],
    equipment: ['trap-bar'],
    tags: ['full-body', 'carry', 'forearms', 'traps', 'compound'],
  },
  {
    key: 'kettlebell-suitcase-carry',
    names: { en: 'Kettlebell suitcase carry', sv: 'Resväskebärning med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.DISTANCE],
    equipment: ['kettlebell'],
    tags: ['full-body', 'carry', 'obliques', 'anti-lateral-flexion', 'unilateral'],
  },
  {
    key: 'kettlebell-waiters-walk',
    names: { en: 'Kettlebell waiters walk', sv: 'Servitörsbärning med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.DISTANCE],
    equipment: ['kettlebell'],
    tags: ['full-body', 'carry', 'front-delts', 'unilateral'],
  },
  {
    key: 'barbell-overhead-carry',
    names: { en: 'Barbell overhead carry', sv: 'Bärning med skivstång över huvudet' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.DISTANCE],
    equipment: ['barbell'],
    tags: ['full-body', 'carry', 'front-delts', 'abs'],
  },
  {
    key: 'barbell-zercher-carry',
    names: { en: 'Barbell Zercher carry', sv: 'Zercherbärning med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.DISTANCE],
    equipment: ['barbell'],
    tags: ['full-body', 'carry', 'abs', 'traps'],
  },
  {
    key: 'sandbag-carry',
    names: { en: 'Sandbag carry', sv: 'Bärning med sandsäck' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.DISTANCE],
    equipment: ['sandbag'],
    tags: ['full-body', 'carry', 'abs', 'traps'],
  },
  {
    key: 'barbell-power-clean',
    names: { en: 'Barbell power clean', sv: 'Frivändning med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['full-body', 'olympic', 'hinge', 'traps', 'quadriceps', 'compound'],
  },
  {
    key: 'barbell-hang-clean',
    names: { en: 'Barbell hang clean', sv: 'Frivändning från häng' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['full-body', 'olympic', 'hinge', 'traps', 'compound'],
  },
  {
    key: 'barbell-clean-and-jerk',
    names: { en: 'Barbell clean and jerk', sv: 'Frivändning och stöt' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['full-body', 'olympic', 'vertical-push', 'quadriceps', 'compound'],
  },
  {
    key: 'barbell-snatch',
    names: { en: 'Barbell snatch', sv: 'Ryck med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['full-body', 'olympic', 'hinge', 'traps', 'compound'],
  },
  {
    key: 'barbell-push-jerk',
    names: { en: 'Barbell push jerk', sv: 'Stöt med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['full-body', 'olympic', 'vertical-push', 'triceps', 'compound'],
  },
  {
    key: 'barbell-thruster',
    names: { en: 'Barbell thruster', sv: 'Thruster med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['full-body', 'squat', 'vertical-push', 'quadriceps', 'compound'],
  },
  {
    key: 'dumbbell-thruster',
    names: { en: 'Dumbbell thruster', sv: 'Thruster med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['full-body', 'squat', 'vertical-push', 'quadriceps', 'compound'],
  },
  {
    key: 'kettlebell-clean-and-press',
    names: { en: 'Kettlebell clean and press', sv: 'Frivändning och press med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['full-body', 'hinge', 'vertical-push', 'compound'],
  },
  {
    key: 'kettlebell-snatch',
    names: { en: 'Kettlebell snatch', sv: 'Ryck med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['full-body', 'hinge', 'vertical-push', 'conditioning', 'compound'],
  },
  {
    key: 'kettlebell-turkish-get-up',
    names: { en: 'Turkish get-up', sv: 'Turkish get-up med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['full-body', 'abs', 'front-delts', 'unilateral', 'compound'],
  },
  {
    key: 'burpee',
    names: { en: 'Burpee', sv: 'Burpees' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['full-body', 'conditioning', 'plyometric', 'bodyweight'],
  },
  {
    key: 'bear-crawl',
    names: { en: 'Bear crawl', sv: 'Björnkrypning' },
    metrics: [ExerciseMetric.TIME],
    equipment: ['bodyweight'],
    tags: ['full-body', 'conditioning', 'abs', 'bodyweight'],
  },
  {
    key: 'box-jump',
    names: { en: 'Box jump', sv: 'Boxhopp' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['box', 'bodyweight'],
    tags: ['full-body', 'plyometric', 'quadriceps', 'bodyweight'],
  },
  {
    key: 'broad-jump',
    names: { en: 'Broad jump', sv: 'Stående längdhopp' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['full-body', 'plyometric', 'quadriceps', 'bodyweight'],
  },
  {
    key: 'battle-rope-wave',
    names: { en: 'Battle rope wave', sv: 'Battle ropes' },
    metrics: [ExerciseMetric.TIME],
    equipment: ['battle-ropes'],
    tags: ['full-body', 'conditioning', 'front-delts'],
  },
  {
    key: 'sled-push',
    names: { en: 'Sled push', sv: 'Slädpush' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.DISTANCE],
    equipment: ['sled'],
    tags: ['full-body', 'conditioning', 'quadriceps', 'glutes'],
  },
  {
    key: 'sled-pull',
    names: { en: 'Sled pull', sv: 'Släddrag' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.DISTANCE],
    equipment: ['sled'],
    tags: ['full-body', 'conditioning', 'hamstrings', 'lats'],
  },
  {
    key: 'medicine-ball-slam',
    names: { en: 'Medicine ball slam', sv: 'Medicinbollsslam' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['medicine-ball'],
    tags: ['full-body', 'conditioning', 'abs', 'lats'],
  },
  {
    key: 'wall-ball',
    names: { en: 'Wall ball', sv: 'Wall balls' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['medicine-ball'],
    tags: ['full-body', 'squat', 'vertical-push', 'conditioning'],
  },
  {
    key: 'barbell-hip-thrust',
    names: { en: 'Barbell hip thrust', sv: 'Höftlyft med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell', 'bench'],
    tags: ['glutes', 'hinge', 'hamstrings', 'compound'],
  },
  {
    key: 'barbell-glute-bridge',
    names: { en: 'Barbell glute bridge', sv: 'Bäckenlyft med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['glutes', 'hinge', 'hamstrings', 'compound'],
  },
  {
    key: 'barbell-romanian-deadlift',
    names: { en: 'Barbell Romanian deadlift', sv: 'Rumänskt marklyft med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['glutes', 'hinge', 'hamstrings', 'lower-back', 'compound'],
  },
  {
    key: 'barbell-stiff-leg-deadlift',
    names: { en: 'Barbell stiff-leg deadlift', sv: 'Marklyft med raka ben' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['glutes', 'hinge', 'hamstrings', 'compound'],
  },
  {
    key: 'barbell-good-morning',
    names: { en: 'Barbell good morning', sv: 'Good morning med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['glutes', 'hinge', 'hamstrings', 'lower-back', 'compound'],
  },
  {
    key: 'dumbbell-romanian-deadlift',
    names: { en: 'Dumbbell Romanian deadlift', sv: 'Rumänskt marklyft med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['glutes', 'hinge', 'hamstrings', 'compound'],
  },
  {
    key: 'dumbbell-single-leg-romanian-deadlift',
    names: { en: 'Single-leg Romanian deadlift', sv: 'Enbens rumänskt marklyft med hantel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['glutes', 'hinge', 'hamstrings', 'unilateral'],
  },
  {
    key: 'dumbbell-hip-thrust',
    names: { en: 'Dumbbell hip thrust', sv: 'Höftlyft med hantel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell', 'bench'],
    tags: ['glutes', 'hinge', 'hamstrings'],
  },
  {
    key: 'kettlebell-swing',
    names: { en: 'Kettlebell swing', sv: 'Kettlebellsving' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['glutes', 'hinge', 'hamstrings', 'conditioning', 'compound'],
  },
  {
    key: 'kettlebell-deadlift',
    names: { en: 'Kettlebell deadlift', sv: 'Marklyft med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['glutes', 'hinge', 'hamstrings', 'compound'],
  },
  {
    key: 'kettlebell-single-leg-deadlift',
    names: { en: 'Kettlebell single-leg deadlift', sv: 'Enbens marklyft med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['glutes', 'hinge', 'hamstrings', 'unilateral'],
  },
  {
    key: 'cable-pull-through',
    names: { en: 'Cable pull-through', sv: 'Pull-through i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['glutes', 'hinge', 'hamstrings'],
  },
  {
    key: 'cable-glute-kickback',
    names: { en: 'Cable glute kickback', sv: 'Bakåtspark i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['glutes', 'isolation', 'unilateral'],
  },
  {
    key: 'cable-hip-abduction',
    names: { en: 'Cable hip abduction', sv: 'Abduktion i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['glutes', 'abductors', 'isolation'],
  },
  {
    key: 'machine-back-extension',
    names: { en: 'Machine back extension', sv: 'Ryggresning i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['glutes', 'hinge', 'lower-back', 'hamstrings'],
  },
  {
    key: 'hyperextension',
    names: { en: 'Hyperextension', sv: 'Ryggresning i ryggbänk' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['hyperextension-bench', 'bodyweight'],
    tags: ['glutes', 'hinge', 'lower-back', 'hamstrings', 'bodyweight'],
  },
  {
    key: 'machine-hip-thrust',
    names: { en: 'Machine hip thrust', sv: 'Höftlyft i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['glutes', 'hinge', 'hamstrings'],
  },
  {
    key: 'machine-hip-abduction',
    names: { en: 'Hip abduction', sv: 'Abduktion i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['glutes', 'abductors', 'isolation'],
  },
  {
    key: 'band-good-morning',
    names: { en: 'Band good morning', sv: 'Good morning med gummiband' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['glutes', 'hinge', 'hamstrings'],
  },
  {
    key: 'band-hip-thrust',
    names: { en: 'Band hip thrust', sv: 'Höftlyft med gummiband' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['glutes', 'hinge', 'hamstrings'],
  },
  {
    key: 'band-lateral-walk',
    names: { en: 'Band lateral walk', sv: 'Sidosteg med gummiband' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['glutes', 'abductors', 'isolation'],
  },
  {
    key: 'band-glute-kickback',
    names: { en: 'Band glute kickback', sv: 'Bakåtspark med gummiband' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['glutes', 'isolation', 'unilateral'],
  },
  {
    key: 'glute-bridge',
    names: { en: 'Glute bridge', sv: 'Bäckenlyft' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['glutes', 'hinge', 'hamstrings', 'bodyweight'],
  },
  {
    key: 'single-leg-glute-bridge',
    names: { en: 'Single-leg glute bridge', sv: 'Enbens bäckenlyft' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['glutes', 'hinge', 'hamstrings', 'unilateral', 'bodyweight'],
  },
  {
    key: 'glute-ham-raise',
    names: { en: 'Glute ham raise', sv: 'Glute ham raise' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['glute-ham-bench', 'bodyweight'],
    tags: ['glutes', 'hinge', 'hamstrings', 'bodyweight', 'compound'],
  },
  {
    key: 'barbell-back-squat',
    names: { en: 'Barbell back squat', sv: 'Knäböj med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell', 'squat-rack'],
    tags: ['legs', 'squat', 'quadriceps', 'glutes', 'compound'],
  },
  {
    key: 'barbell-front-squat',
    names: { en: 'Barbell front squat', sv: 'Frontböj med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell', 'squat-rack'],
    tags: ['legs', 'squat', 'quadriceps', 'glutes', 'compound'],
  },
  {
    key: 'barbell-box-squat',
    names: { en: 'Barbell box squat', sv: 'Boxknäböj med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell', 'squat-rack', 'box'],
    tags: ['legs', 'squat', 'quadriceps', 'glutes', 'compound'],
  },
  {
    key: 'barbell-pause-squat',
    names: { en: 'Barbell pause squat', sv: 'Knäböj med paus' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell', 'squat-rack'],
    tags: ['legs', 'squat', 'quadriceps', 'compound'],
  },
  {
    key: 'zercher-squat',
    names: { en: 'Zercher squat', sv: 'Zercherböj' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['legs', 'squat', 'quadriceps', 'abs', 'compound'],
  },
  {
    key: 'smith-machine-squat',
    names: { en: 'Smith machine squat', sv: 'Knäböj i smithmaskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['smith-machine'],
    tags: ['legs', 'squat', 'quadriceps', 'glutes', 'compound'],
  },
  {
    key: 'dumbbell-squat',
    names: { en: 'Dumbbell squat', sv: 'Knäböj med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['legs', 'squat', 'quadriceps', 'glutes', 'compound'],
  },
  {
    key: 'dumbbell-goblet-squat',
    names: { en: 'Dumbbell goblet squat', sv: 'Goblet squat med hantel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['legs', 'squat', 'quadriceps', 'glutes', 'compound'],
  },
  {
    key: 'kettlebell-goblet-squat',
    names: { en: 'Kettlebell goblet squat', sv: 'Goblet squat med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['legs', 'squat', 'quadriceps', 'glutes', 'compound'],
  },
  {
    key: 'kettlebell-front-squat',
    names: { en: 'Kettlebell front squat', sv: 'Frontböj med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['legs', 'squat', 'quadriceps', 'compound'],
  },
  {
    key: 'bodyweight-squat',
    names: { en: 'Bodyweight squat', sv: 'Knäböj med kroppsvikt' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['legs', 'squat', 'quadriceps', 'glutes', 'bodyweight'],
  },
  {
    key: 'jump-squat',
    names: { en: 'Jump squat', sv: 'Hoppknäböj' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['legs', 'squat', 'quadriceps', 'plyometric', 'bodyweight'],
  },
  {
    key: 'pistol-squat',
    names: { en: 'Pistol squat', sv: 'Enbensknäböj' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['legs', 'squat', 'quadriceps', 'unilateral', 'bodyweight'],
  },
  {
    key: 'wall-sit',
    names: { en: 'Wall sit', sv: 'Väggsits' },
    metrics: [ExerciseMetric.TIME],
    equipment: ['bodyweight'],
    tags: ['legs', 'quadriceps', 'isometric', 'bodyweight'],
  },
  {
    key: 'machine-hack-squat',
    names: { en: 'Machine hack squat', sv: 'Hack squat i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['legs', 'squat', 'quadriceps', 'glutes', 'compound'],
  },
  {
    key: 'leg-press',
    names: { en: 'Leg press', sv: 'Benpress' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['legs', 'squat', 'quadriceps', 'glutes', 'compound'],
  },
  {
    key: 'single-leg-press',
    names: { en: 'Single-leg press', sv: 'Enbens benpress' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['legs', 'squat', 'quadriceps', 'unilateral', 'compound'],
  },
  {
    key: 'machine-belt-squat',
    names: { en: 'Machine belt squat', sv: 'Bältesböj i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['legs', 'squat', 'quadriceps', 'glutes', 'compound'],
  },
  {
    key: 'barbell-deadlift',
    names: { en: 'Barbell deadlift', sv: 'Marklyft med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['legs', 'hinge', 'hamstrings', 'glutes', 'lower-back', 'traps', 'compound'],
  },
  {
    key: 'barbell-sumo-deadlift',
    names: { en: 'Barbell sumo deadlift', sv: 'Sumomarklyft med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['legs', 'hinge', 'glutes', 'adductors', 'hamstrings', 'compound'],
  },
  {
    key: 'barbell-deficit-deadlift',
    names: { en: 'Barbell deficit deadlift', sv: 'Marklyft från förhöjning' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['legs', 'hinge', 'hamstrings', 'glutes', 'lower-back', 'compound'],
  },
  {
    key: 'trap-bar-deadlift',
    names: { en: 'Trap bar deadlift', sv: 'Marklyft med trap bar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['trap-bar'],
    tags: ['legs', 'hinge', 'quadriceps', 'glutes', 'hamstrings', 'compound'],
  },
  {
    key: 'nordic-hamstring-curl',
    names: { en: 'Nordic hamstring curl', sv: 'Nordisk hamstringcurl' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight', 'glute-ham-bench'],
    tags: ['legs', 'hinge', 'hamstrings', 'bodyweight', 'compound'],
  },
  {
    key: 'barbell-lunge',
    names: { en: 'Barbell lunge', sv: 'Utfallssteg med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['legs', 'lunge', 'quadriceps', 'glutes', 'unilateral', 'compound'],
  },
  {
    key: 'barbell-split-squat',
    names: { en: 'Barbell split squat', sv: 'Split squat med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['legs', 'lunge', 'quadriceps', 'glutes', 'unilateral', 'compound'],
  },
  {
    key: 'dumbbell-walking-lunge',
    names: { en: 'Dumbbell walking lunge', sv: 'Gående utfall med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['legs', 'lunge', 'quadriceps', 'glutes', 'unilateral', 'compound'],
  },
  {
    key: 'dumbbell-reverse-lunge',
    names: { en: 'Dumbbell reverse lunge', sv: 'Utfall bakåt med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['legs', 'lunge', 'quadriceps', 'glutes', 'unilateral'],
  },
  {
    key: 'dumbbell-bulgarian-split-squat',
    names: { en: 'Dumbbell Bulgarian split squat', sv: 'Bulgarisk utfallsböj med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell', 'bench'],
    tags: ['legs', 'lunge', 'quadriceps', 'glutes', 'unilateral', 'compound'],
  },
  {
    key: 'dumbbell-lateral-lunge',
    names: { en: 'Dumbbell lateral lunge', sv: 'Sidoutfall med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['legs', 'lunge', 'adductors', 'quadriceps', 'unilateral'],
  },
  {
    key: 'dumbbell-step-up',
    names: { en: 'Dumbbell step-up', sv: 'Uppsteg med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell', 'box'],
    tags: ['legs', 'lunge', 'quadriceps', 'glutes', 'unilateral'],
  },
  {
    key: 'kettlebell-reverse-lunge',
    names: { en: 'Kettlebell reverse lunge', sv: 'Utfall bakåt med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['legs', 'lunge', 'quadriceps', 'glutes', 'unilateral'],
  },
  {
    key: 'bodyweight-lunge',
    names: { en: 'Bodyweight lunge', sv: 'Utfallssteg med kroppsvikt' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['legs', 'lunge', 'quadriceps', 'glutes', 'unilateral', 'bodyweight'],
  },
  {
    key: 'machine-leg-extension',
    names: { en: 'Leg extension', sv: 'Benspark i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['legs', 'quadriceps', 'isolation'],
  },
  {
    key: 'machine-lying-leg-curl',
    names: { en: 'Lying leg curl', sv: 'Liggande lårcurl i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['legs', 'hamstrings', 'isolation'],
  },
  {
    key: 'machine-seated-leg-curl',
    names: { en: 'Seated leg curl', sv: 'Sittande lårcurl i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['legs', 'hamstrings', 'isolation'],
  },
  {
    key: 'band-leg-curl',
    names: { en: 'Band leg curl', sv: 'Lårcurl med gummiband' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['legs', 'hamstrings', 'isolation'],
  },
  {
    key: 'standing-calf-raise',
    names: { en: 'Standing calf raise', sv: 'Stående tåhävning' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['legs', 'calves', 'isolation'],
  },
  {
    key: 'seated-calf-raise',
    names: { en: 'Seated calf raise', sv: 'Sittande tåhävning' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['legs', 'calves', 'isolation'],
  },
  {
    key: 'dumbbell-calf-raise',
    names: { en: 'Dumbbell calf raise', sv: 'Tåhävning med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['legs', 'calves', 'isolation'],
  },
  {
    key: 'barbell-calf-raise',
    names: { en: 'Barbell calf raise', sv: 'Tåhävning med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['legs', 'calves', 'isolation'],
  },
  {
    key: 'machine-hip-adduction',
    names: { en: 'Hip adduction', sv: 'Adduktion i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['legs', 'adductors', 'isolation'],
  },
  {
    key: 'barbell-overhead-press',
    names: { en: 'Barbell overhead press', sv: 'Militärpress med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['shoulders', 'vertical-push', 'front-delts', 'triceps', 'compound'],
  },
  {
    key: 'barbell-push-press',
    names: { en: 'Barbell push press', sv: 'Push press med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['shoulders', 'vertical-push', 'front-delts', 'triceps', 'compound'],
  },
  {
    key: 'barbell-behind-the-neck-press',
    names: { en: 'Behind-the-neck press', sv: 'Nackpress med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['shoulders', 'vertical-push', 'side-delts', 'triceps', 'compound'],
  },
  {
    key: 'barbell-upright-row',
    names: { en: 'Barbell upright row', sv: 'Upprätt rodd med skivstång' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['barbell'],
    tags: ['shoulders', 'side-delts', 'traps', 'compound'],
  },
  {
    key: 'smith-machine-shoulder-press',
    names: { en: 'Smith machine shoulder press', sv: 'Axelpress i smithmaskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['smith-machine'],
    tags: ['shoulders', 'vertical-push', 'front-delts', 'triceps', 'compound'],
  },
  {
    key: 'landmine-press',
    names: { en: 'Landmine press', sv: 'Landminepress' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['landmine', 'barbell'],
    tags: ['shoulders', 'vertical-push', 'front-delts', 'triceps', 'unilateral', 'compound'],
  },
  {
    key: 'dumbbell-shoulder-press',
    names: { en: 'Dumbbell shoulder press', sv: 'Axelpress med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['shoulders', 'vertical-push', 'front-delts', 'triceps', 'compound'],
  },
  {
    key: 'arnold-press',
    names: { en: 'Arnold press', sv: 'Arnoldpress' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['shoulders', 'vertical-push', 'front-delts', 'side-delts', 'compound'],
  },
  {
    key: 'dumbbell-lateral-raise',
    names: { en: 'Dumbbell lateral raise', sv: 'Sidolyft med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['shoulders', 'side-delts', 'isolation'],
  },
  {
    key: 'dumbbell-front-raise',
    names: { en: 'Dumbbell front raise', sv: 'Framåtlyft med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['shoulders', 'front-delts', 'isolation'],
  },
  {
    key: 'dumbbell-rear-delt-fly',
    names: { en: 'Dumbbell rear delt fly', sv: 'Omvänd hantelflyes' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['shoulders', 'rear-delts', 'isolation'],
  },
  {
    key: 'dumbbell-upright-row',
    names: { en: 'Dumbbell upright row', sv: 'Upprätt rodd med hantlar' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['shoulders', 'side-delts', 'traps'],
  },
  {
    key: 'cuban-press',
    names: { en: 'Cuban press', sv: 'Cubanpress' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['dumbbell'],
    tags: ['shoulders', 'rear-delts', 'side-delts', 'isolation'],
  },
  {
    key: 'plate-front-raise',
    names: { en: 'Plate front raise', sv: 'Framåtlyft med viktskiva' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['plate'],
    tags: ['shoulders', 'front-delts', 'isolation'],
  },
  {
    key: 'kettlebell-overhead-press',
    names: { en: 'Kettlebell overhead press', sv: 'Axelpress med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['shoulders', 'vertical-push', 'front-delts', 'triceps', 'unilateral', 'compound'],
  },
  {
    key: 'kettlebell-push-press',
    names: { en: 'Kettlebell push press', sv: 'Push press med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['shoulders', 'vertical-push', 'front-delts', 'triceps', 'compound'],
  },
  {
    key: 'kettlebell-bottoms-up-press',
    names: { en: 'Kettlebell bottoms-up press', sv: 'Bottoms-up-press med kettlebell' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['kettlebell'],
    tags: ['shoulders', 'vertical-push', 'front-delts', 'forearms', 'unilateral'],
  },
  {
    key: 'cable-overhead-press',
    names: { en: 'Cable overhead press', sv: 'Axelpress i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['shoulders', 'vertical-push', 'front-delts', 'triceps', 'compound'],
  },
  {
    key: 'cable-lateral-raise',
    names: { en: 'Cable lateral raise', sv: 'Sidolyft i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['shoulders', 'side-delts', 'isolation'],
  },
  {
    key: 'cable-front-raise',
    names: { en: 'Cable front raise', sv: 'Framåtlyft i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['shoulders', 'front-delts', 'isolation'],
  },
  {
    key: 'cable-rear-delt-fly',
    names: { en: 'Cable rear delt fly', sv: 'Omvänd flyes i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['shoulders', 'rear-delts', 'isolation'],
  },
  {
    key: 'cable-face-pull',
    names: { en: 'Cable face pull', sv: 'Face pull i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['shoulders', 'rear-delts', 'rhomboids', 'traps'],
  },
  {
    key: 'cable-upright-row',
    names: { en: 'Cable upright row', sv: 'Upprätt rodd i kabel' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['cable'],
    tags: ['shoulders', 'side-delts', 'traps'],
  },
  {
    key: 'machine-shoulder-press',
    names: { en: 'Machine shoulder press', sv: 'Axelpress i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['shoulders', 'vertical-push', 'front-delts', 'triceps', 'compound'],
  },
  {
    key: 'machine-lateral-raise',
    names: { en: 'Machine lateral raise', sv: 'Sidolyft i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['shoulders', 'side-delts', 'isolation'],
  },
  {
    key: 'machine-reverse-fly',
    names: { en: 'Machine reverse fly', sv: 'Omvänd flyes i maskin' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['machine'],
    tags: ['shoulders', 'rear-delts', 'rhomboids', 'isolation'],
  },
  {
    key: 'band-overhead-press',
    names: { en: 'Band overhead press', sv: 'Axelpress med gummiband' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['shoulders', 'vertical-push', 'front-delts', 'triceps'],
  },
  {
    key: 'band-lateral-raise',
    names: { en: 'Band lateral raise', sv: 'Sidolyft med gummiband' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['shoulders', 'side-delts', 'isolation'],
  },
  {
    key: 'band-pull-apart',
    names: { en: 'Band pull-apart', sv: 'Isärdragning med gummiband' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['shoulders', 'rear-delts', 'rhomboids'],
  },
  {
    key: 'band-face-pull',
    names: { en: 'Band face pull', sv: 'Face pull med gummiband' },
    metrics: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
    equipment: ['band'],
    tags: ['shoulders', 'rear-delts', 'traps'],
  },
  {
    key: 'pike-push-up',
    names: { en: 'Pike push-up', sv: 'Armhävning i pikeposition' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['shoulders', 'vertical-push', 'front-delts', 'triceps', 'bodyweight'],
  },
  {
    key: 'handstand-push-up',
    names: { en: 'Handstand push-up', sv: 'Armhävning i handstående' },
    metrics: [ExerciseMetric.REPS],
    equipment: ['bodyweight'],
    tags: ['shoulders', 'vertical-push', 'front-delts', 'triceps', 'bodyweight', 'compound'],
  },
]
