// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file api/v1/options.proto (package api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodOptions, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from extension: bool requires_auth = 50001;
 */
export const requires_auth = proto3.makeExtension<MethodOptions, boolean>(
  "api.v1.requires_auth", 
  MethodOptions, 
  { no: 50001, kind: "scalar", T: 8 /* ScalarType.BOOL */ },
);

