DROP TABLE IF EXISTS public.plan_routines CASCADE;
DROP TABLE IF EXISTS public.plans CASCADE;
DROP TABLE IF EXISTS public.events CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.auth_rate_limits CASCADE;
DROP TABLE IF EXISTS public.traces CASCADE;
DROP TABLE IF EXISTS public.workout_comments CASCADE;
DROP TABLE IF EXISTS public.workout_likes CASCADE;
DROP TABLE IF EXISTS public.followers CASCADE;
DROP TABLE IF EXISTS public.personal_bests CASCADE;
DROP TABLE IF EXISTS public.sets CASCADE;
DROP TABLE IF EXISTS public.workout_group_exercises CASCADE;
DROP TABLE IF EXISTS public.workout_groups CASCADE;
DROP TABLE IF EXISTS public.workouts CASCADE;
DROP TABLE IF EXISTS public.exercises_routines CASCADE;
DROP TABLE IF EXISTS public.routine_groups CASCADE;
DROP TABLE IF EXISTS public.routine_exercises CASCADE;
DROP TABLE IF EXISTS public.exercises CASCADE;
DROP TABLE IF EXISTS public.routines CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.auth CASCADE;
DROP TYPE IF EXISTS public.event_topic;
DROP TYPE IF EXISTS public.routine_group_mode;
DROP TYPE IF EXISTS public.notification_type;
DROP TYPE IF EXISTS public.routine_group_role;
DROP TYPE IF EXISTS public.routine_exercise_tracking;
DROP FUNCTION IF EXISTS public.exercises_refresh_personal_bests();
DROP FUNCTION IF EXISTS public.sets_refresh_personal_bests();
DROP FUNCTION IF EXISTS public.sets_promote_personal_bests();
DROP FUNCTION IF EXISTS public.refresh_personal_bests(UUID[], UUID[]);
DROP FUNCTION IF EXISTS public.personal_best_rank(TEXT[], DOUBLE PRECISION, INT, DOUBLE PRECISION, INT);
