name: Apply Terraform

inputs:
  aws_access_key_id:
    description: "AWS Access Key ID"
    required: true
  aws_secret_access_key:
    description: "AWS Secret Access Key"
    required: true
  db_username:
    description: "Database Username"
    required: true
  db_password:
    description: "Database Password"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.1.7

    - name: Terraform Init
      run: terraform init
      working-directory: ./infra
      shell: bash

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: ./infra
      shell: bash
      env:
        TF_LOG: DEBUG

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./infra
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        TF_VAR_db_username: ${{ inputs.db_username }}
        TF_VAR_db_password: ${{ inputs.db_password }}
