#!/usr/bin/env bash
set -euo pipefail

# Writes the local environment files for the current checkout so that several
# worktrees can run the stack at the same time without sharing ports, Docker
# containers, or databases.
#
# The main checkout keeps the documented defaults. Every other worktree is
# assigned a slot: a contiguous block of ports starting at 20000 + slot * 20.
# The slot is derived from the worktree path so it stays stable across runs, and
# is recorded in mise.local.toml so an already configured worktree is never
# renumbered.

readonly SLOT_BASE=20000
readonly SLOT_WIDTH=20
readonly SLOT_COUNT=99

root="$(git rev-parse --show-toplevel)"
name="$(basename "$root")"
local_toml="$root/mise.local.toml"

# The main checkout has a .git directory; worktrees have a .git file.
if [[ -d "$root/.git" ]]; then
  echo "Main checkout detected, keeping the default ports."
  exit 0
fi

port_in_use() {
  nc -z 127.0.0.1 "$1" >/dev/null 2>&1
}

slot_is_free() {
  local base=$(($SLOT_BASE + $1 * $SLOT_WIDTH)) index
  for index in $(seq 0 8); do
    if port_in_use $((base + index)); then
      return 1
    fi
  done
  return 0
}

set_env() {
  local file=$1 key=$2 value=$3 tmp
  tmp="$(mktemp)"
  if grep -q "^${key}=" "$file"; then
    awk -v key="$key" -v value="$value" -F= \
      '$1 == key { print key "=" value; next } { print }' "$file" >"$tmp"
    mv "$tmp" "$file"
  else
    rm -f "$tmp"
    printf '%s=%s\n' "$key" "$value" >>"$file"
  fi
}

slot=""
if [[ -f "$local_toml" ]]; then
  slot="$(awk -F'"' '/^WORKTREE_SLOT =/ { print $2 }' "$local_toml")"
fi

if [[ -z "$slot" ]]; then
  slot=$(($(printf '%s' "$root" | cksum | cut -d' ' -f1) % SLOT_COUNT + 1))
  for _ in $(seq 1 "$SLOT_COUNT"); do
    if slot_is_free "$slot"; then
      break
    fi
    slot=$((slot % SLOT_COUNT + 1))
  done
fi

base=$((SLOT_BASE + slot * SLOT_WIDTH))
db_port=$((base + 0))
server_port=$((base + 1))
sse_port=$((base + 2))
web_port=$((base + 3))
e2e_web_port=$((base + 4))
e2e_server_port=$((base + 5))
e2e_sse_port=$((base + 6))
mailhog_smtp_port=$((base + 7))
mailhog_http_port=$((base + 8))

cat >"$local_toml" <<TOML
# Generated by 'mise run worktree:env'. Not tracked by Git.
[env]
WORKTREE_SLOT = "$slot"
DB_CONTAINER = "getstronger-$name"
MAILHOG_CONTAINER = "getstronger-mailhog-$name"
MAILHOG_SMTP_PORT = "$mailhog_smtp_port"
MAILHOG_HTTP_PORT = "$mailhog_http_port"
WEB_DEV_PORT = "$web_port"
E2E_WEB_PORT = "$e2e_web_port"
E2E_SERVER_PORT = "$e2e_server_port"
E2E_SSE_PORT = "$e2e_sse_port"
TOML

test -f "$root/.env" || cp "$root/.env.example" "$root/.env"
test -f "$root/web/.env" || cp "$root/web/.env.example" "$root/web/.env"

set_env "$root/.env" DB_PORT "$db_port"
set_env "$root/.env" SERVER_PORT "$server_port"
set_env "$root/.env" SSE_PORT "$sse_port"
set_env "$root/.env" CORS_ALLOWED_ORIGIN "http://localhost:$web_port"
# The backend reads .env rather than the mise environment, so it needs its own
# copy of the port this worktree's MailHog publishes.
set_env "$root/.env" MAILHOG_SMTP_PORT "$mailhog_smtp_port"
set_env "$root/web/.env" VITE_API_URL "http://localhost:$server_port"

cat <<SUMMARY
✅  Configured worktree '$name' as slot $slot

  database      $db_port (container getstronger-$name)
  backend       $server_port
  sse           $sse_port
  web           http://localhost:$web_port
  mailhog       http://localhost:$mailhog_http_port
  e2e web       $e2e_web_port
  e2e backend   $e2e_server_port

Run 'mise run db:init && mise run db:migrate && mise run db:seed' to create this
worktree's database.
SUMMARY
