name: Validate Terraform

runs:
  using: 'composite'
  steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Format Check
      run: terraform fmt -check -recursive -diff
      working-directory: ./infra
      shell: bash

    - name: Terraform Init
      run: terraform init
      working-directory: ./infra
      shell: bash

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./infra
      shell: bash
