name: Validate Terraform

runs:
  using: 'composite'
  steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.1.7

    - name: Terraform Format Check
      run: terraform fmt -check -recursive
      working-directory: ./infra

    - name: Terraform Init
      run: terraform init
      working-directory: ./infra

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./infra
