name: Deploy on Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply Terraform
        uses: ./.github/actions/apply/terraform

      - name: Migrate database
        uses: ./.github/actions/migrate/database

      - name: Deploy web app to S3
        uses: ./.github/actions/deploy/web-app
