name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - labeled
  workflow_dispatch:
    inputs:
      migrate:
        description: Run pending database migrations
        required: true
        default: true
        type: boolean
      deploy_server:
        description: Deploy the API to the Scaleway Instance
        required: true
        default: true
        type: boolean
      deploy_web:
        description: Deploy the web app to Scaleway Object Storage
        required: true
        default: true
        type: boolean

concurrency:
  group: deployments
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: write
  checks: read
  statuses: read
  actions: read
  repository-projects: read

jobs:
  init:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.label.name == 'deploy' && github.actor == 'crlssn')
    runs-on: ubuntu-latest

    outputs:
      web: ${{ steps.changes.outputs.web }}
      server: ${{ steps.changes.outputs.server }}
      database: ${{ steps.changes.outputs.database }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes
        id: changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        with:
          filters: |
            web: ['web/**']
            server: ['server/**', 'go.mod', 'go.sum', 'mise.toml']
            database: ['database/**']

  database:
    needs: init
    runs-on: ubuntu-latest
    if: needs.init.outputs.database == 'true' || (github.event_name == 'workflow_dispatch' && inputs.migrate)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install golang-migrate
        run: |
          wget https://github.com/golang-migrate/migrate/releases/download/v4.19.1/migrate.linux-amd64.deb
          sudo dpkg -i migrate.linux-amd64.deb

      - name: Run migration
        env:
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_MIGRATION_USER: ${{ vars.DB_MIGRATION_USER }}
          DB_MIGRATION_PASSWORD: ${{ secrets.DB_MIGRATION_PASSWORD }}
        run: |
          migrate -path database/migrations/ \
            -database "postgresql://${DB_MIGRATION_USER}:${DB_MIGRATION_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require" \
            -verbose up

  server:
    needs: [init, database]
    runs-on: ubuntu-latest
    if: >-
      always() &&
      (needs.database.result == 'success' || needs.database.result == 'skipped') &&
      (needs.init.outputs.server == 'true' || (github.event_name == 'workflow_dispatch' && inputs.deploy_server))

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Build binary
        working-directory: ./server
        run: |
          go mod download
          GOOS=linux go build -o bin/app cmd/main.go

      - name: Create env file
        working-directory: ./server/bin
        run: |
          {
            echo ENV=production
            echo DB_HOST=${{ vars.DB_HOST }}
            echo DB_PORT=${{ vars.DB_PORT }}
            echo DB_USER=${{ vars.DB_USER }}
            echo DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            echo DB_NAME=${{ vars.DB_NAME }}
            echo CORS_ALLOWED_ORIGIN=${{ vars.CORS_ALLOWED_ORIGIN }}
            echo SERVER_PORT=${{ vars.SERVER_PORT }}
            echo SERVER_CERT_PATH=${{ vars.SERVER_CERT_PATH }}
            echo SERVER_KEY_PATH=${{ vars.SERVER_KEY_PATH }}
            echo COOKIE_DOMAIN=${{ vars.COOKIE_DOMAIN }}
            echo JWT_ACCESS_TOKEN_KEY=${{ secrets.JWT_ACCESS_TOKEN_KEY }}
            echo JWT_REFRESH_TOKEN_KEY=${{ secrets.JWT_REFRESH_TOKEN_KEY }}
            echo EMAIL_PROVIDER=${{ vars.EMAIL_PROVIDER }}
            echo EMAIL_FROM_ADDRESS=${{ vars.EMAIL_FROM_ADDRESS }}
            echo SCW_PROJECT_ID=${{ vars.SCW_PROJECT_ID }}
            echo SCW_TEM_REGION=${{ vars.SCW_TEM_REGION }}
            echo SCW_TEM_SECRET_KEY=${{ secrets.SCW_TEM_SECRET_KEY }}
          } >> .env

      - name: Deploy to Scaleway Instance
        uses: easingthemes/ssh-deploy@ece05a22752e524363164bfb2f69a5ba4f8ded0d # v5.1.0
        with:
          REMOTE_HOST: ${{ vars.SCW_INSTANCE_HOST }}
          REMOTE_USER: ${{ vars.SCW_INSTANCE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SCW_INSTANCE_SSH_KEY }}
          SOURCE: 'server/bin/'
          TARGET: ${{ vars.SCW_INSTANCE_APP_DIR }}

      - name: Restart service
        uses: appleboy/ssh-action@7eaf76671a0d7eec5d98ee897acda4f968735a17 # v1.2.0
        with:
          host: ${{ vars.SCW_INSTANCE_HOST }}
          username: ${{ vars.SCW_INSTANCE_USER }}
          key: ${{ secrets.SCW_INSTANCE_SSH_KEY }}
          port: 22
          script: |
            cd "${{ vars.SCW_INSTANCE_APP_DIR }}"
            ./app

  web:
    needs: [init, server]
    runs-on: ubuntu-latest
    if: >-
      always() &&
      (needs.server.result == 'success' || needs.server.result == 'skipped') &&
      (needs.init.outputs.web == 'true' || (github.event_name == 'workflow_dispatch' && inputs.deploy_web))

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        working-directory: ./web
        run: npm install

      - name: Build the app
        working-directory: ./web
        run: npm run build
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          VITE_API_URL: ${{ vars.VITE_API_URL }}

      - name: Deploy to Scaleway Object Storage
        working-directory: ./web
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.SCW_REGION }}
          SCW_REGION: ${{ vars.SCW_REGION }}
          SCW_BUCKET_NAME: ${{ vars.SCW_BUCKET_NAME }}
        run: |
          mkdir ~/.aws
          echo "[default]
          aws_access_key_id = ${{ secrets.SCW_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.SCW_SECRET_KEY }}
          " >> ~/.aws/credentials
          cat ~/.aws/credentials
          echo "
          [default]
          region = ${{ vars.SCW_REGION }}
          output = json
          
          s3 =
            max_concurrent_requests = 100
            max_queue_size = 1000
            multipart_threshold = 50 MB
            multipart_chunksize = 10 MB
            endpoint_url = https://s3.${{ vars.SCW_REGION }}.scw.cloud
          " >> ~/.aws/config
          cat ~/.aws/config
          echo aws s3 sync ./dist "s3://${{ vars.SCW_BUCKET_NAME }}" --delete --endpoint-url "https://${{ vars.SCW_BUCKET_NAME }}.s3.${{ vars.SCW_REGION }}.scw.cloud"
          aws s3 sync ./dist "s3://${{ vars.SCW_BUCKET_NAME }}" --delete --endpoint-url "https://${{ vars.SCW_BUCKET_NAME }}.s3.${{ vars.SCW_REGION }}.scw.cloud"

  cleanup:
    needs: [init, database, server, web]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove deploy label
        if: github.event_name == 'pull_request' && github.event.label.name == 'deploy'
        run: gh pr edit ${{ github.event.pull_request.number }} --remove-label "deploy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
