name: Lint

on:
  pull_request:
    paths:
      - 'protobufs/**'

jobs:
  protobufs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install protolint
        run: go install github.com/yoheimuta/protolint/cmd/protolint@latest

      - name: Run protolint
        working-directory: ./protobufs
        run: protolint .
